[package]
name = "zsa_wallet"
authors = []
version = "0.1.0"
edition = "2018"

[dependencies]
clap = "4"
serde = { version = "1", features = ["serde_derive"] }
thiserror = "1"
reqwest = { version = "0.11", features = ["blocking", "json"] }

# Diesel ORM
diesel = { version = "2.1.0", features = ["sqlite"] }
dotenvy = "0.15"

# Zcash
incrementalmerkletree = "0.4"
bridgetree = "0.3"
byteorder = "1"

orchard = "0.5"
zcash_primitives = "0.12"
zebra-chain = "1.0.0-beta.28"

[dependencies.abscissa_core]
version = "0.7.0"

[dev-dependencies]
abscissa_core = { version = "0.7.0", features = ["testing"] }
once_cell = "1.2"

[patch.crates-io]
orchard = { version = "0.5", git = "https://github.com/QED-it/orchard", branch = "ivk-to-bytes-visibility-downgrade" }
zcash_primitives = { version = "0.12", git = "https://github.com/QED-it/librustzcash.git", branch = "zsa-bundle-in-v5-vector-serialization" }
#zcash_encoding = { version = "0.2", git = "https://github.com/QED-it/librustzcash.git", branch = "zsa-bundle-in-v5-vector-serialization" }
