[package]
name = "zsa_wallet"
authors = []
version = "0.1.0"
edition = "2018"

[dependencies]
clap = "4"
serde = { version = "1", features = ["serde_derive"] }
thiserror = "1"
reqwest = { version = "0.11", features = ["blocking", "json"] }

# Diesel ORM
diesel = { version = "2.1.0", features = ["sqlite", "returning_clauses_for_sqlite_3_35"] }
dotenvy = "0.15"

# Zcash
incrementalmerkletree = "0.5.0"
bridgetree = "0.4.0"
byteorder = "1"

orchard = { version = "0.7.0", path = "../orchard" }
zcash_primitives = { version = "0.13.0-rc.1", features = ["transparent-inputs"] }
zcash_note_encryption = "0.4.0"
zcash_encoding = "0.2.0"
zcash_address = "0.3.0"
zcash_client_backend = "0.10.0-rc.1"
zcash_proofs = "0.13.0-rc.1"

serde_json = "1.0.105"
hex = { version = "0.4.3", features = ["serde"] }
rand = "0.8.5"

# - Transparent inputs
ripemd = { version = "0.1" }
sha2 = "0.10"
secp256k1 = { version = "0.26" }

[dependencies.abscissa_core]
version = "0.7.0"

[dev-dependencies]
abscissa_core = { version = "0.7.0", features = ["testing"] }
once_cell = "1.2"

[patch.crates-io]

zcash_note_encryption = { version = "0.4.0", path = "../../../CLionProjects/librustzcash/components/zcash_note_encryption" }
zcash_primitives = { version = "0.13.0-rc.1", path = "../../../CLionProjects/librustzcash/zcash_primitives" }
zcash_address = { version = "0.3.0", path = "../../../CLionProjects/librustzcash/components/zcash_address" }
zcash_client_backend = { version = "0.10.0-rc.1", path = "../../../CLionProjects/librustzcash/zcash_client_backend" }
zcash_proofs = { version = "0.13.0-rc.1", path = "../../../CLionProjects/librustzcash/zcash_proofs" }
zcash_encoding = { version = "0.2.0", path = "../../../CLionProjects/librustzcash/components/zcash_encoding" }