[package]
name = "zcash_tx_tool"
authors = []
version = "0.3.2"
edition = "2018"
build = "build.rs"

[dependencies]
clap = "4"
serde = { version = "1", features = ["serde_derive"] }
thiserror = "1"
reqwest = { version = "0.11", features = ["blocking", "json"] }

# Diesel ORM
diesel = { version = "2.1.0", features = ["sqlite", "returning_clauses_for_sqlite_3_35"] }
dotenvy = "0.15"

# Zcash
incrementalmerkletree = "0.5.0"
bridgetree = "0.4.0"
byteorder = "1"

orchard = "0.8.0"
zcash_primitives = { version = "0.15.0", features = ["transparent-inputs"] }
zcash_protocol = { version = "0.1.1" }
zcash_note_encryption = "0.4.0"
zcash_encoding = "0.2.0"
zcash_address = "0.3.2"
zcash_client_backend = "0.12.1"
zcash_proofs = "0.15.0"

serde_json = "1.0.105"
hex = { version = "0.4.3", features = ["serde"] }
rand = "0.8.5"
blake2b_simd = "=1.0.1"

# - Transparent inputs
ripemd = { version = "0.1" }
sha2 = "0.10"
secp256k1 = { version = "0.26" }

[dependencies.abscissa_core]
version = "0.7.0"

[dev-dependencies]
abscissa_core = { version = "0.7.0", features = ["testing"] }
once_cell = "1.2"

[patch.crates-io]
orchard = { git = "https://github.com/QED-it/orchard", rev = "831ca109705a409bc3d3b82e76245e45dd0f0812" }
sapling-crypto = { git = "https://github.com/QED-it/sapling-crypto", branch = "zsa1" }
zcash_note_encryption = { git = "https://github.com/QED-it/zcash_note_encryption", branch = "zsa1" }
zcash_primitives = { git = "https://github.com/QED-it/librustzcash", rev = "e88964e248c9038e757771b8225c47ac8772abc4" }
zcash_protocol = { git = "https://github.com/QED-it/librustzcash", rev = "e88964e248c9038e757771b8225c47ac8772abc4" }
zcash_address = { git = "https://github.com/QED-it/librustzcash", rev = "e88964e248c9038e757771b8225c47ac8772abc4" }
zcash_client_backend = { git = "https://github.com/QED-it/librustzcash", rev = "e88964e248c9038e757771b8225c47ac8772abc4" }
zcash_proofs = { git = "https://github.com/QED-it/librustzcash", rev = "e88964e248c9038e757771b8225c47ac8772abc4" }
zcash_encoding = { git = "https://github.com/QED-it/librustzcash", rev = "e88964e248c9038e757771b8225c47ac8772abc4" }
