[package]
name = "zcash_tx_tool"
authors = []
version = "0.4.0"
edition = "2024"
build = "build.rs"

[dependencies]
clap = "4"
serde = { version = "1", features = ["serde_derive"] }
thiserror = "1"
reqwest = { version = "0.11", features = ["blocking", "json"] }

# Diesel ORM
diesel = { version = "2.1.0", features = ["sqlite", "returning_clauses_for_sqlite_3_35"] }
dotenvy = "0.15"

# Zcash
incrementalmerkletree = "0.8.2"
bridgetree = "0.7.0"
byteorder = "1"

orchard = "0.11.0"
zcash_primitives = { version = "0.23.0", features = ["transparent-inputs", "non-standard-fees"] }
zcash_protocol = { version = "0.5.3" }
zcash_note_encryption = "0.4.1"
zcash_encoding = "0.3.0"
zcash_address = "0.8.0"
zcash_client_backend = "0.19.0"
zcash_proofs = "0.23.0"

serde_json = "1.0.105"
hex = { version = "0.4.3", features = ["serde"] }
rand = "0.8.5"
blake2b_simd = "=1.0.1"
bip0039 = "0.12.0"
nonempty = "0.11.0"

# - Transparent inputs
zcash_transparent = { version = "0.3.0", features = ["transparent-inputs"] }
ripemd = { version = "0.1" }
sha2 = "0.10"
secp256k1 = { version = "0.29.1" }

[dependencies.abscissa_core]
version = "0.7.0"

[dev-dependencies]
abscissa_core = { version = "0.7.0", features = ["testing"] }
once_cell = "1.2"

[lints.rust]
non_local_definitions = "allow"

[patch.crates-io]
orchard = { git = "https://github.com/QED-it/orchard", rev = "0982ff66e15e3e1e0566e4c9cd688d9d0e5d4f81" }
sapling-crypto = { git = "https://github.com/QED-it/sapling-crypto", rev = "b0d2e4c1139f23fb7e9e410f2e5d986d5662ee03" }
zcash_note_encryption = { version = "0.4.1", git = "https://github.com/zcash/zcash_note_encryption", rev = "668ea44cf59a226715a5f3cb1bf88710a8c188a3" }
zcash_primitives = { git = "https://github.com/QED-it/librustzcash", rev = "583aba3eeedec277e00da1f0ac73286d82a0488e" }
zcash_protocol = { git = "https://github.com/QED-it/librustzcash", rev = "583aba3eeedec277e00da1f0ac73286d82a0488e" }
zcash_address = { git = "https://github.com/QED-it/librustzcash", rev = "583aba3eeedec277e00da1f0ac73286d82a0488e" }
zcash_client_backend = { git = "https://github.com/QED-it/librustzcash", rev = "583aba3eeedec277e00da1f0ac73286d82a0488e" }
zcash_proofs = { git = "https://github.com/QED-it/librustzcash", rev = "583aba3eeedec277e00da1f0ac73286d82a0488e" }
zcash_encoding = { git = "https://github.com/QED-it/librustzcash", rev = "583aba3eeedec277e00da1f0ac73286d82a0488e" }
zcash_transparent = { git = "https://github.com/QED-it/librustzcash", rev = "583aba3eeedec277e00da1f0ac73286d82a0488e" }
