FROM rust:1.81.0

# Set up Rust and cargo
RUN apt-get update && apt-get install git build-essential clang -y

# Checkout and build custom branch, tag, or commit of the zebra repository
ARG ref=zsa-integration-demo-ag

# Add a simple cache busting mechanism
# This will invalidate the cache whenever the repository is updated
ADD https://api.github.com/repos/QED-it/zebra/commits/HEAD version.json

# Clone the repository and checkout the specified reference
RUN git clone https://github.com/QED-it/zebra.git && \
    cd zebra && \
    git fetch --all --tags && \
    git checkout ${ref}

WORKDIR zebra

RUN cargo build --release --package zebrad --bin zebrad --features="getblocktemplate-rpcs"

EXPOSE 18232

COPY regtest-config.toml regtest-config.toml

# Run the zebra node
ENTRYPOINT ["target/release/zebrad", "-c", "regtest-config.toml"]
