name: Lints

# We only run these lints on trial-merges of PRs to reduce noise.
on: pull_request

jobs:

  fmt:
    name: Rustfmt
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo fmt -- --check

  clippy:
    name: Clippy (MSRV)
    timeout-minutes: 30
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: '--cfg zcash_unstable="nu6"'
    steps:
      - uses: actions/checkout@v4
      - name: Run Clippy
        uses: auguwu/clippy-action@1.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: ${{ inputs.target }}
          deny: warnings
