name: CI Workflow to ECR and Zebra (merged-PR gate)

# 1️⃣  Fire only when a PR targeting `main` is closed.
#     We’ll bail out immediately unless that PR was merged.
on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  trigger-on-merge:
    # 2️⃣  Continue only if the PR was merged
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest

    steps:
      # 3️⃣  Make sure *this* commit’s run of
      #     “Check tx-tool against Zebra” concluded **success**.
      - name: Verify Zebra check workflow succeeded
        id: zebra
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const {owner, repo} = context.repo;
            const mergeSha = context.payload.pull_request.merge_commit_sha;

            // Get the runs of that particular workflow on the merge commit
            const runs = await github.rest.actions.listWorkflowRuns({
              owner,
              repo,
              workflow_id: 'check-tx-tool-against-zebra.yaml',   // file name OR numeric ID
              head_sha: mergeSha
            });

            const ok = runs.data.workflow_runs
              .some(run => run.conclusion === 'success');

            core.setOutput('passed', ok);
            if (!ok) {
              core.setFailed('Zebra check did not succeed on the merge commit');
            }

      # 4️⃣  Dispatch the downstream workflows only if step #3 passed
      - name: Trigger push-to-ECR workflow
        if: steps.zebra.outputs.passed == 'true'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'push-to-ecr.yaml',
              ref: 'main'
            });

      - name: Trigger Zebra push-deploy workflow
        if: steps.zebra.outputs.passed == 'true'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: 'zebra',
              workflow_id: 'push-deploy.yaml',
              ref: 'zsa-integration-demo-ag'
            });
